=== wherehappy/Happit/grimace-v1.1/meta/facedata01.dtd
<!-- basic types -->

<!ELEMENT facedata ( feature | musclegroup | emotion| overlay | underlays )* >


<!-- splines and points -->

<!ELEMENT spline ( point+ ) >
<!ATTLIST spline id ID #IMPLIED >
<!ATTLIST spline type ( line | quadraticbezier | cubicbezier | joiner ) #REQUIRED >

<!ELEMENT point EMPTY >
<!ATTLIST point id ID #IMPLIED >
<!ATTLIST point ref IDREF #IMPLIED >
<!ATTLIST point x NMTOKEN #IMPLIED >
<!ATTLIST point y NMTOKEN #IMPLIED >


<!-- muscles -->

<!ELEMENT musclegroup ( muscle* ) >
<!ATTLIST musclegroup id ID #REQUIRED >
<!ATTLIST musclegroup alpha NMTOKEN #REQUIRED >
<!ATTLIST musclegroup color NMTOKEN #REQUIRED >
<!ATTLIST musclegroup visible NMTOKEN #REQUIRED >
<!ATTLIST musclegroup width NMTOKEN #REQUIRED >
<!ATTLIST musclegroup zindex NMTOKEN #IMPLIED >

<!ELEMENT muscle ( spline ) >
<!ATTLIST muscle id ID #REQUIRED >
<!ATTLIST muscle inittension NMTOKEN #IMPLIED >
<!ATTLIST muscle label NMTOKEN #IMPLIED >


<!-- features -->

<!ELEMENT feature ( fill | segment )* >
<!ATTLIST feature filled ( true | false ) #IMPLIED >
<!ATTLIST feature mirrored ( true | false ) #IMPLIED >
<!ATTLIST feature static ( true | false ) #IMPLIED >
<!ATTLIST feature stroked ( true | false ) #IMPLIED >
<!ATTLIST feature zindex NMTOKEN #IMPLIED >

<!ELEMENT fill ( draw, addmuscle? ) >

<!ELEMENT segment ( spline, strokestyle?, alphamapping?, addmuscle* ) >
<!ATTLIST segment id ID #REQUIRED >
<!ATTLIST segment label CDATA #IMPLIED >
<!ATTLIST segment alpha NMTOKEN #REQUIRED >
<!ATTLIST segment color NMTOKEN #REQUIRED >
<!ATTLIST segment width NMTOKEN #REQUIRED >

<!ELEMENT strokestyle ( values ) >
<!ATTLIST strokestyle type ( brush ) #REQUIRED >

<!ELEMENT values EMPTY >
<!ATTLIST values alpha NMTOKEN "1.0" >
<!ATTLIST values color NMTOKEN #IMPLIED >
<!ATTLIST values endwidth NMTOKEN #IMPLIED >
<!ATTLIST values maxwidth NMTOKEN #IMPLIED >
<!ATTLIST values startwidth NMTOKEN #IMPLIED >
<!ATTLIST values x0 NMTOKEN #IMPLIED >
<!ATTLIST values x1 NMTOKEN #IMPLIED >
<!ATTLIST values y0 NMTOKEN #IMPLIED >
<!ATTLIST values y1 NMTOKEN #IMPLIED >
<!ATTLIST values mean NMTOKEN #IMPLIED >
<!ATTLIST values value NMTOKEN #IMPLIED >
<!ATTLIST values variance NMTOKEN #IMPLIED >


<!ELEMENT alphamapping ( mapping ) >
<!ATTLIST alphamapping group NMTOKEN #REQUIRED >
<!ATTLIST alphamapping sourcemuscle NMTOKEN #REQUIRED >

<!ELEMENT addmuscle EMPTY >
<!ATTLIST addmuscle group IDREF #REQUIRED >
<!ATTLIST addmuscle muscle IDREF #REQUIRED >
<!ATTLIST addmuscle nodenum ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED >
<!ATTLIST addmuscle weight NMTOKEN #REQUIRED >


<!-- emotions -->

<!ELEMENT emotion ( addinfluence* ) >
<!ATTLIST emotion id ID #REQUIRED >
<!ATTLIST emotion label NMTOKEN #IMPLIED >

<!ELEMENT addinfluence ( mapping ) >
<!ATTLIST addinfluence group NMTOKEN #REQUIRED >
<!ATTLIST addinfluence muscle NMTOKEN #REQUIRED >
<!ATTLIST addinfluence priority NMTOKEN "1.0" >


<!-- mappings -->

<!ELEMENT mapping ( values, param* ) >
<!ATTLIST mapping type ( gauss | polynomial | sine  ) #REQUIRED >

<!ELEMENT param EMPTY >
<!ATTLIST param exponent NMTOKEN #REQUIRED >
<!ATTLIST param value NMTOKEN #REQUIRED >


<!-- drawing API -->
<!ELEMENT draw ( beginFill | curveTo | drawCircle | drawEllipse | drawRect | endFill | lineStyle | lineTo | moveTo )* >

<!ELEMENT beginFill EMPTY >
<!ATTLIST beginFill alpha NMTOKEN #REQUIRED >
<!ATTLIST beginFill color NMTOKEN #REQUIRED >

<!ELEMENT curveTo EMPTY >
<!ATTLIST curveTo anchorX NMTOKEN #REQUIRED >
<!ATTLIST curveTo anchorY NMTOKEN #REQUIRED >
<!ATTLIST curveTo controlX NMTOKEN #REQUIRED >
<!ATTLIST curveTo controlY NMTOKEN #REQUIRED >

<!ELEMENT drawCircle EMPTY >
<!ATTLIST drawCircle radius NMTOKEN #REQUIRED >
<!ATTLIST drawCircle x NMTOKEN #REQUIRED >
<!ATTLIST drawCircle y NMTOKEN #REQUIRED >

<!ELEMENT drawEllipse EMPTY >
<!ATTLIST drawEllipse height NMTOKEN #REQUIRED >
<!ATTLIST drawEllipse width NMTOKEN #REQUIRED >
<!ATTLIST drawEllipse x NMTOKEN #REQUIRED >
<!ATTLIST drawEllipse y NMTOKEN #REQUIRED >

<!ELEMENT drawRect EMPTY >
<!ATTLIST drawRect height NMTOKEN #REQUIRED >
<!ATTLIST drawRect width NMTOKEN #REQUIRED >
<!ATTLIST drawRect x NMTOKEN #REQUIRED >
<!ATTLIST drawRect y NMTOKEN #REQUIRED >

<!ELEMENT endFill EMPTY >

<!ELEMENT lineStyle EMPTY >
<!ATTLIST lineStyle alpha NMTOKEN #REQUIRED >
<!ATTLIST lineStyle color NMTOKEN #REQUIRED >
<!ATTLIST lineStyle thickness NMTOKEN #REQUIRED >

<!ELEMENT lineTo EMPTY >
<!ATTLIST lineTo x NMTOKEN #REQUIRED >
<!ATTLIST lineTo y NMTOKEN #REQUIRED >

<!ELEMENT moveTo EMPTY >
<!ATTLIST moveTo x NMTOKEN #REQUIRED >
<!ATTLIST moveTo y NMTOKEN #REQUIRED >


<!-- underlays -->

<!ELEMENT underlays ( underlaygroup* ) >

<!ELEMENT underlaygroup ( image* ) >
<!ATTLIST underlaygroup base_url CDATA #REQUIRED >
<!ATTLIST underlaygroup id CDATA #REQUIRED >

<!ELEMENT image EMPTY >
<!ATTLIST image id CDATA #REQUIRED >
<!ATTLIST image url CDATA #REQUIRED >
<!ATTLIST image dx NMTOKEN #REQUIRED >
<!ATTLIST image dy NMTOKEN #REQUIRED >
<!ATTLIST image alpha NMTOKEN #REQUIRED >
<!ATTLIST image scale NMTOKEN #REQUIRED >


<!-- overlays -->

<!ELEMENT overlay EMPTY >
<!ATTLIST overlay alpha NMTOKEN #REQUIRED >
<!ATTLIST overlay id NMTOKEN #REQUIRED >
<!ATTLIST overlay scale NMTOKEN #REQUIRED >
<!ATTLIST overlay url CDATA #REQUIRED >
<!ATTLIST overlay x NMTOKEN #REQUIRED >
<!ATTLIST overlay y NMTOKEN #REQUIRED >

=== wherehappy/Happit/grimace-v1.1/demos/js/head.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE facedata PUBLIC "-//grimace//DTD facedata 0.1//EN"
  "http://grimace-project.net/dtd/facedata01.dtd">
<facedata>
	<!-- HEAD -->
	<feature stroked='true' filled='true' mirrored='true' static='true'>
		<fill>
				<draw>
					<beginFill color="0xF1E2D6" alpha="1" />
					<drawRect x="-200" y="-30" width="400" height="530" />
					<endFill />
				</draw>
			</fill>
		<segment id="fh1" label="headtop" color="0x222222" width="4" alpha="1">
			<spline type="joiner" id="fh1s">
				<point id="fhp1"  x="-10" y="-24"/>
				<point id="fhp2"  x="0"   y="-24"/>
				<point id="fhp3"  x="150" y="23"/>
				<point id="fhp4"  x="180" y="51"/>
			</spline>
		</segment>
		<segment id="fh2" label="headside" color="0x222222" width="4" alpha="1">
			<spline type="cubicbezier" id="fh2s">
				<point ref="fhp3"/>
				<point id="fhp5"  x="197" y="180"/>
				<point id="fhp6"  x="193" y="285"/>
				<point id="fhp7"  x="146" y="397"/>
			</spline>
		</segment>
		<segment id="fh3" label="headbottom" color="0x222222" width="4" alpha="1">
			<spline type="joiner" id="fh3s">
				<point ref="fhp6"/>
				<point ref="fhp7"/>
				<point id="fhp8"  x="0" y="497"/>
				<point id="fhp9"  x="-10" y="497"/>
			</spline>
		</segment>
	</feature>
	
	<!-- NOSE -->
	<feature stroked='true' mirrored='true'>
		<segment id="n1" label="nose1" color="0x222222" width="3" alpha="1">
			<spline type="joiner" id="n1s">
				<point id="n1_p0" x="-5" y="333"/>
				<point id="n1_p1" x="0" y="333"/>
				<point id="n2_p0" x="23" y="326"/>
				<point id="n2_p1" x="36" y="329"/>
			</spline>
			<strokestyle type="brush">
				<values startwidth="0.5" maxwidth="1" endwidth="1" color="0x222222" alpha="1"/>
			</strokestyle>
		</segment>
		<segment id='n2' label='nose2' color="0x222222" width="3" alpha="1">
			<spline type="cubicbezier" id="n2s">
				<point ref="n2_p0"/>
				<point ref="n2_p1"/>
				<point id="n2_p2" x="47" y="326"/>
				<point id="n2_p3" x="44" y="305"/>
			</spline>
			<strokestyle type="brush">
				<values startwidth="1" maxwidth="1" endwidth="1" color="0x222222" alpha="1"/>
			</strokestyle>
		</segment>
	</feature>
</facedata>

=== wherehappy/Happit/grimace-v1.1/docs/facedataexample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facedata PUBLIC "-//grimace//DTD facedata 0.1//EN"
  "http://grimace-project.net/dtd/facedata01.dtd">
<facedata>
	<musclegroup id="feature" color="0xd16d00" width="2" alpha="0.3" zindex="0" visible="false">
		<muscle id="m_lid">
			<spline type="line">
				<point x="107" y="224"/>
				<point x="107" y="152"/>
			</spline>
		</muscle>
	</musclegroup>
	
	<!-- Define an eye -->
	<feature stroked='true' filled='true' mirrored='true'>
		<fill>
			<draw>
				<!-- A set of native drawing commands for the Flash player -->
				<beginFill color="0xffffff" alpha="1" />
				<drawCircle x="84" y="200" radius="100" />
				<endFill />
				<beginFill color="0xB3D5ED" alpha="1" />
				<drawCircle x="84" y="200" radius="17" />
				<endFill />
				<lineStyle thickness="1" color="0x000000" alpha="1" />
				<beginFill color="0x000000" alpha="1" />
				<drawCircle x="84" y="200" radius="6" />
				<endFill />
				<!-- ... repeat for left eye -->
			</draw>
		</fill>
		
		<segment id="f2" label="upperlid" color="0x404040" width="4" alpha="1">
			<!-- Define the shape of this segment -->
			<spline type="cubicbezier" id="s2">
				<!-- Entering an ID for a point saves it for later use -->
				<point id="end_eye_right" x="125" y="205"/>
				<point x="105" y="171"/>
				<point x="60"  y="171"/>
				<point id="end_eye_left" x="43" y="212"/>
			</spline>
			
			<strokestyle type="brush">
				<!-- When a StrokeStyle is supplied, the outline is drawn
				according to the style. Without a style, the outline is
				stroked with the segment's constant thickness. -->
				<values startwidth="1" maxwidth="3" endwidth="2" color="0x404040" alpha="1"/>
			</strokestyle>
			
			<!-- Define muscle dependencies for this segment
			This is the upper eye lid. If it opens, the endpoints remain in
			position while the control points need to be connected to a
			muscle. Since this is a Cubic Bezier, the control points are nodes
			number 1 and 2. -->
			<addmuscle nodenum="1" group="feature" muscle="m_lid" weight="1" />
			<addmuscle nodenum="2" group="feature" muscle="m_lid" weight="0.67" />
		</segment>

		<segment id="f3" label="lowerlid" color="0x404040" width="4" alpha="1">
			<spline type="cubicbezier" id="s3">
				<!-- Supplying the ref parameter with an ID recalls a point -->
				<point ref="end_eye_left"/>
				<point x="56" 	y="206"/>
				<point x="90" 	y="242"/>
				<point ref="end_eye_right"/>
			</spline>
			<!-- ... -->
		</segment>
	</feature>
	
	<emotion id="e2" label="surprise">
		<!-- Configures the influence of surprise on muscles.
		In this example, it only has an influence on muscle m_lid from
		the group feature.
		The priority parameter is necessary when several emotions influence
		the same muscle. -->
		<addinfluence group="feature" muscle="m_lid" priority="3">
			<mapping type="sine">
				<values x0="0.29" x1="0.83" y0="0" y1="1" />
			</mapping>
		</addinfluence>
		<!-- ... -->
	</emotion>
	
	<!-- Add some hair onto this face -->
	<overlay id="hair" url="hairdo.swf" x="-239" y="-87" scale="0.93" alpha="1"/>
</facedata>
